language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev
  
script:
  - echo $TRAVIS_BUILD_NUMBER > .build.info
  - python setup.py bdist_wheel
  - pipenv install --dev -e . 

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master

